- name: Download outline script
  become_user: root
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh
    dest: /tmp/install_server.sh
    mode: '0777'
- name: Install Docker
  become_user: root
  apt:
    name: docker.io
    state: latest
- name: Install Outline
  become_user: root
  shell: bash -c /tmp/install_server.sh > output_outline >> /tmp/outline_output
  register: my_output

- name: copy to local
  fetch:
    src: /tmp/outline_output
    dest: ./outline_output


- debug: var=my_output.stdout_line
